data_ingestion:
  source_url: "https://raw.githubusercontent.com/campusx-official/jupyter-masterclass/main/tweet_emotions.csv"
  allowed_sentiments:
    - sadness
    - happiness
  label_map:
    sadness: 0
    happiness: 1
  test_size: 0.2
  random_state: 42
  out_dir: "data/raw"

feature_engineering:
  max_features: 50

model_training:
  n_estimators: 50
  learning_rate: 0.1
  random_state: 42
